In [11]:
from tensorflow.keras.preprocessing.text import one_hot

In [12]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
## Define the vocabulary size
voc_size=10000

In [14]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[1239, 7234, 5196, 889],
 [1239, 7234, 5196, 9253],
 [1239, 3738, 5196, 3926],
 [5820, 5156, 5882, 9244, 8565],
 [5820, 5156, 5882, 9244, 5219],
 [4797, 1239, 4629, 5196, 3483],
 [241, 3791, 8959, 9244]]

In [15]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
import numpy as np

In [17]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1239 7234 5196  889]
 [   0    0    0    0 1239 7234 5196 9253]
 [   0    0    0    0 1239 3738 5196 3926]
 [   0    0    0 5820 5156 5882 9244 8565]
 [   0    0    0 5820 5156 5882 9244 5219]
 [   0    0    0 4797 1239 4629 5196 3483]
 [   0    0    0    0  241 3791 8959 9244]]


In [18]:
## feature representation
dim=10

In [25]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.build(input_shape=(None, sent_length)) # Explicitly build the model
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step


array([[[ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.04638959,  0.04167566,  0.00548452,  0.01906374,
          0.04297422,  0.01027917, -0.03878782,  0.01707258,
          0.00654224,  0.02745623],
        [ 0.04596479, -0.02735515,  0.045176  , -0.02538738,
         -0.03852285,  0.00730474,  0.01390184,  0.04223111,
          0.02628441, -0.01827451],
        [ 0.00383664, -0.02571386, -0.04477138,  0.0

In [28]:
embedded_docs[0]

array([   0,    0,    0,    0, 1239, 7234, 5196,  889], dtype=int32)

In [30]:
import numpy as np
model.predict(np.array([embedded_docs[0]]))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step


array([[[ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.02775249,  0.04056295, -0.02098018, -0.00891938,
         -0.04006732,  0.01391964,  0.00597333,  0.04164095,
         -0.02054076,  0.0084467 ],
        [ 0.04638959,  0.04167566,  0.00548452,  0.01906374,
          0.04297422,  0.01027917, -0.03878782,  0.01707258,
          0.00654224,  0.02745623],
        [ 0.04596479, -0.02735515,  0.045176  , -0.02538738,
         -0.03852285,  0.00730474,  0.01390184,  0.04223111,
          0.02628441, -0.01827451],
        [ 0.00383664, -0.02571386, -0.04477138,  0.0